name: eliud_pkg_pay
description: Eliud pay package
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  eliud_core:
    path: ../eliud_core

  eliud_pkg_fundamentals:
    path: ../eliud_pkg_fundamentals

  eliud_pkg_workflow:
    path: ../eliud_pkg_workflow

  eliud_pkg_notifications:
    path: ../eliud_pkg_notifications

flutter:
