---
name: eliud_pkg_pay
description: eliud_pkg_pay is a package to provide payment functionality to your eliud
  app. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_pay
version: 1.2.0
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  eliud_core:                                                                                        # ANDROID IOS             WEB
    path: ../../eliud/eliud_core
  eliud_pkg_fundamentals:                                                                            # ANDROID IOS             WEB
    path: ../eliud_pkg_fundamentals
  eliud_pkg_notifications:                                                                           # ANDROID IOS             WEB
    path: ../eliud_pkg_notifications
  eliud_pkg_workflow:                                                                                # ANDROID IOS             WEB
    path: ../eliud_pkg_workflow
  eliud_pkg_workflow_model:                                                                          # ANDROID IOS             WEB
    path: ../eliud_pkg_workflow_model

  flutter:
    sdk: flutter
dev_dependencies:
  lints: ^3.0.0
flutter: null
platforms:
  android: null
  ios: null
  web: null
