---
name: eliud_pkg_pay
description: eliud_pkg_pay is a package to provide payment functionality to your eliud
  app. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_pay
version: 1.2.0
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  bloc: ^8.1.2
  eliud_core:
    path: ../eliud_core
  eliud_core_main:
    path: ../eliud_core_main
  eliud_core_helpers:
    path: ../eliud_core_helpers
  eliud_core_model:
    path: ../eliud_core_model
  eliud_pkg_fundamentals:
    path: ../eliud_pkg_fundamentals
  eliud_pkg_workflow:
    path: ../eliud_pkg_workflow
  eliud_pkg_workflow_model:
    path: ../eliud_pkg_workflow_model
  eliud_pkg_notifications:
    path: ../eliud_pkg_notifications
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter:
    sdk: flutter
dev_dependencies:
  lints: ^3.0.0
flutter: null
platforms:
  android: null
  ios: null
  web: null
