---
name: eliud_pkg_pay
description: eliud_pkg_pay is a package to provide payment functionality to your eliud
  app. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_pay
version: 1.1.5+5
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  bloc: ^8.1.2
  eliud_core: ^1.1.5+7
  eliud_pkg_fundamentals: ^1.1.5+6
  eliud_pkg_workflow: ^1.1.5+5
  eliud_pkg_notifications: ^1.1.5+5
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter:
    sdk: flutter
dev_dependencies:
  lints: ^3.0.0
flutter: null
platforms:
  android: null
  ios: null
  web: null
