---
name: eliud_pkg_pay
description: eliud_pkg_pay is a package to provide payment functionality to your eliud
  app. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_pay
version: 1.3.0
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  eliud_core: ^1.3.0
  eliud_core_helpers: ^1.3.0
  eliud_core_model: ^1.3.0
  eliud_pkg_fundamentals: ^1.3.0
  eliud_pkg_notifications: ^1.3.0
  eliud_pkg_workflow: ^1.3.0
  eliud_pkg_workflow_model: ^1.3.0
  eliud_core_main: ^1.3.0
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter:
    sdk: flutter
dev_dependencies:
  lints: ^5.0.0
flutter: null
platforms:
  android: null
  ios: null
  web: null
