---
name: eliud_pkg_pay
description: Eliud pay package
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_pay
version: 1.0.1+7
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  cloud_functions: ^4.2.0
  bloc: ^8.1.0
  equatable: ^2.0.5
  eliud_core: ^1.0.6+1
  eliud_pkg_fundamentals: ^1.0.1+6
  eliud_pkg_workflow: ^1.0.1+6
  eliud_pkg_notifications: ^1.0.1+6
flutter: null
platforms:
  android: null
  ios: null
  web: null
